### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by NileshEvonix** [adityak368/FileBrowser#6] opened 2017-11-10 13:05 UTC
Unexpected crash in adapter. Please fix this asap 

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=109; index=-1
       at java.util.ArrayList.get(ArrayList.java:413)
       **at com.aditya.filebrowser.adapters.CustomAdapter.getItemAt(CustomAdapter.java:197)
       at com.aditya.filebrowser.FileChooser$1.onItemClick(FileChooser.java:175)
       _at com.aditya.filebrowser.adapters.CustomAdapterItemClickListener.onInterceptTouchEvent(CustomAdapterItemClickListener.java:46)_**
       at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2658)
       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2786)
       at android.view.View.dispatchTouchEvent(View.java:10024)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3065)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
       at android.view.View.dispatchPointerEvent(View.java:10244)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4450)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4318)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4011)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4068)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6259)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6233)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6194)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6362)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by adityak368** [comment] 2017-11-10 14:21
Can you please let me know the steps to reproduce it? Or may be let me know when does this happen?

**Comment by NileshEvonix** [comment] 2017-11-11 07:09
Just scroll list down-up fast. App will slow down then go back to previous activity.

**Comment by adityak368** [comment] 2017-11-11 07:43
I am not able to reproduce it. Can you give me some more info? or some steps to reproduce

**Comment by adityak368** [comment] 2017-11-11 10:59
I have made a fix based on intuition. Please let me know if it is fixed. You can also close the issue if it is fixed.
please check v1.7

**Comment by alanwoolley** [comment] 2018-02-02 01:48
I've integrated v1.7 in to my app and I'm also seeing this error in my Google Play Console, so I don't think it's fixed I'm afraid. I've also been unable to reproduce it myself.

**Comment by adityak368** [comment] 2018-07-06 12:48
Could u please share the logs from the console?

**Comment by adityak368** [comment] 2019-06-30 19:29
Closing as cannot reproduce

**Closed as completed by adityak368** 2019-06-30 19:29 UTC
